config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomePageView, MessageView

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('message/', MessageView.as_view(), name='message'),
]

users/urls.py
from django import urls

app_name = 'users'

urlpatterns = [

]

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class PopularCarModel(models.Model):
    brand = models.CharField(max_length=50, verbose_name=_('brand'))
    image = models.ImageField(upload_to='popular_car/', verbose_name=_('image'))
    model = models.CharField(max_length=30, verbose_name=_('model'))
    condition = models.CharField(max_length=30, verbose_name=_('condition'))
    year = models.CharField(max_length=4, verbose_name=_('year'))
    motor_type = models.CharField(max_length=30, verbose_name=_('motor type'))
    fuel = models.CharField(max_length=30, verbose_name=_('fuel'))
    price = models.DecimalField(max_digits=6, decimal_places=3, verbose_name=_('price'))
    max_speed = models.CharField(max_length=3, verbose_name='maximal speed')
    is_active = models.BooleanField(default=False, blank=True, verbose_name=_('is active'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.brand

    class Meta:
        verbose_name = _('popular car')
        verbose_name_plural = _('popular cars')


class FeaturedCarModel(models.Model):
    brand = models.CharField(max_length=50, verbose_name=_('brand'))
    image = models.ImageField(upload_to='popular_car/', verbose_name=_('image'))
    model = models.CharField(max_length=30, verbose_name=_('model'))
    price = models.DecimalField(max_digits=6, decimal_places=3, verbose_name=_('price'))
    is_active = models.BooleanField(default=False, blank=True, verbose_name=_('is active'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.brand

    class Meta:
        verbose_name = _('featured car')
        verbose_name_plural = _('featured cars')


class MessageModel(models.Model):
    name = models.CharField(max_length=40, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    subject = models.CharField(max_length=50, verbose_name=_('subject'))
    message = models.TextField(verbose_name=_('message'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('message')
        verbose_name_plural = _('messages')

users/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import MessageModel


class MessageModelForm(forms.ModelForm):

    class Meta:
        model = MessageModel
        exclude = ['created_at']

main/views.py
from django.shortcuts import render, reverse
from django.views.generic import TemplateView, CreateView
from .models import PopularCarModel, FeaturedCarModel, MessageModel
from .forms import MessageModelForm
from django.core.mail import send_mail
from django.conf.global_settings import EMAIL_HOST_USER
from .utils import send_bot_message


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['popular_cars'] = PopularCarModel.objects.all().filter(is_active=True)
        data['featured_cars'] = FeaturedCarModel.objects.order_by('-id').filter(is_active=True)[:4]
        data['featured_cars2'] = FeaturedCarModel.objects.order_by('-id').filter(is_active=True)[4:8]
        return data


class MessageView(CreateView):
    model = MessageModel
    form_class = MessageModelForm
    template_name = 'layouts/contact.html'

    def get_success_url(self,):
        return reverse('main:home')

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        # message = f"Assalomu alaykum {form.instance.name}! xabaringizni qabul qildim."
        # send_mail("Yangi xabar", message, EMAIL_HOST_USER, [form.instance.email])
        send_bot_message(form.cleaned_data)
        return super().form_valid(form)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}


    <section class="home" id="home">

        <h3 data-speed="-2" class="home-parallax">find your car</h3>

        <img data-speed="5" class="home-parallax" src="{% static 'image/home-img.png' %}" alt="">

        <a data-speed="7" href="#vehicles" class="btn home-parallax">explore cars</a>

    </section>

    <section class="icons-container">

        <div class="icons">
            <i class="fas fa-home"></i>
            <div class="content">
                <h3>150+</h3>
                <p>branches</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>4770+</h3>
                <p>cars sold</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-users"></i>
            <div class="content">
                <h3>320+</h3>
                <p>happy clients</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>1500+</h3>
                <p>news cars</p>
            </div>
        </div>

    </section>

    <section class="vehicles" id="vehicles">

        <h1 class="heading"> popular <span>vehicles</span></h1>

        <div class="swiper vehicles-slider">

            <div class="swiper-wrapper">
                {% for popular_car in popular_cars %}
                    <div class="swiper-slide box">
                        <img src="{{ popular_car.image.url }}" alt="">
                        <div class="content">
                            <h3>{{ popular_car.brand }}: <i class="text-secondary">{{ popular_car.model }}</i></h3>
                            <div class="price"><span>price : </span> ${{ popular_car.price }}/-</div>
                            <p>
                                {{ popular_car.condition }}
                                <span class="fas fa-circle"></span> {{ popular_car.year }}
                                <span class="fas fa-circle"></span> {{ popular_car.motor_type }}
                                <span class="fas fa-circle"></span> {{ popular_car.fuel }}
                                <span class="fas fa-circle"></span> {{ popular_car.max_speed }}km/h
                            </p>
                            {% if request.user.is_authenticated %}
                                <a href="#" class="btn">check out</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="swiper-pagination"></div>

        </div>

    </section>

    <section class="featured" id="featured">

        <h1 class="heading"><span>featured</span> cars </h1>

        <div class="swiper featured-slider">

            <div class="swiper-wrapper">
                {% for featured_car in featured_cars.select_related %}
                    <div class="swiper-slide box">
                        <img src="{{ featured_car.image.url }}" alt="">
                        <div class="content">
                            <h3>{{ featured_car.brand }}</h3>
                            <div class="stars">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star-half-alt"></i>
                            </div>
                            <div class="price">${{ featured_car.price }}/-</div>
                            {% if request.user.is_authenticated %}
                                <a href="#" class="btn">check out</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="swiper-pagination"></div>

        </div>

        <div class="swiper featured-slider">
            <div class="swiper-wrapper">
                {% for featured_car in featured_cars2 %}
                    <div class="swiper-slide box">
                        <img src="{{ featured_car.image.url }}" alt="">
                        <div class="content">
                            <h3>{{ featured_car.brand }}</h3>
                            <div class="stars">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star-half-alt"></i>
                            </div>
                            <div class="price">${{ featured_car.price }}/-</div>
                            {% if request.user.is_authenticated %}
                                <a href="#" class="btn">check out</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination"></div>

        </div>

    </section>

    <section class="newsletter">

        <h3>subscribe for latest updates</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, suscipit.</p>

        <form action="">
            <input type="email" placeholder="enter your email">
            <input type="submit" value="subscribe">
        </form>

    </section>

    <section class="reviews" id="reviews">

        <h1 class="heading"> client's <span>review</span></h1>

        <div class="swiper review-slider">

            <div class="swiper-wrapper">

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-1.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-2.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-3.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-4.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-5.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

                <div class="swiper-slide box">
                    <img src="{% static 'image/pic-6.png' %}" alt="">
                    <div class="content">
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium
                            iusto
                            id autem possimus assumenda at ut saepe.</p>
                        <h3>john deo</h3>
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        </div>
                    </div>
                </div>

            </div>

            <div class="swiper-pagination"></div>

        </div>

    </section>

{% endblock %}

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car selling website</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

{% include 'layouts/navbar.html' %}

{% include 'layouts/login_form.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/contact.html' %}

{% include 'layouts/footer.html' %}


<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/layouts/contact.html
<section class="contact" id="contact">

    <h1 class="heading"><span>contact</span> us</h1>

    <div class="row">

        <iframe class="map"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30153.788252261566!2d72.82321484621745!3d
                    19.141690214227783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b63aceef0c69%3A0x2aa80cf2
                    287dfa3b!2sJogeshwari%20West%2C%20Mumbai%2C%20Maharashtra%20400047!5e0!3m2!1sen!2sin!4v1632137920043
                    !5m2!1sen!2sin"
                allowfullscreen="" loading="lazy"></iframe>

        <form method="post" action="{% url 'main:message' %}">
            {% csrf_token %}
            <h3>get in touch</h3>
            <input name="name" type="text" placeholder="your name" class="box">
            <input name="email" type="email" placeholder="your email" class="box">
            <input name="subject" type="tel" placeholder="subject" class="box">
            <textarea name="message" placeholder="your message" class="box" cols="30" rows="10"></textarea>
            <input type="submit" value="send message" class="btn">
        </form>

    </div>

</section>

templates/layouts/footer.html
<section class="footer" id="footer">

    <div class="box-container">

        <div class="box">
            <h3>our branches</h3>
            <a href="https://www.google.com/maps/dir//%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9
            +%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%A2%D0%B5%D1%
            85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0
            %B5%D1%82,+2+Universitet+St,+Tashkent,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3525
            405,69.2045495,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x38ae8c3da3c6e5c3:0x9882f2a6b7329d1d!2m2!1d69.2067382!2d41.3
            525405"> <i class="fas fa-map-marker-alt"></i> india </a>
            <a href="https://www.google.com/maps/dir//%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9
            +%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%A2%D0%B5%D1%
            85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0
            %B5%D1%82,+2+Universitet+St,+Tashkent,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3525
            405,69.2045495,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x38ae8c3da3c6e5c3:0x9882f2a6b7329d1d!2m2!1d69.2067382!2d41.3
            525405"> <i class="fas fa-map-marker-alt"></i> japan </a>
            <a href="https://www.google.com/maps/dir//%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9
            +%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%A2%D0%B5%D1%
            85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0
            %B5%D1%82,+2+Universitet+St,+Tashkent,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3525
            405,69.2045495,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x38ae8c3da3c6e5c3:0x9882f2a6b7329d1d!2m2!1d69.2067382!2d41.3
            525405"> <i class="fas fa-map-marker-alt"></i> france </a>
            <a href="https://www.google.com/maps/dir//%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9
            +%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%A2%D0%B5%D1%
            85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0
            %B5%D1%82,+2+Universitet+St,+Tashkent,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3525
            405,69.2045495,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x38ae8c3da3c6e5c3:0x9882f2a6b7329d1d!2m2!1d69.2067382!2d41.3
            525405"> <i class="fas fa-map-marker-alt"></i> russia </a>
            <a href="https://www.google.com/maps/dir//%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9
            +%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9+%D0%A2%D0%B5%D1%
            85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9+%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0
            %B5%D1%82,+2+Universitet+St,+Tashkent,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3525
            405,69.2045495,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x38ae8c3da3c6e5c3:0x9882f2a6b7329d1d!2m2!1d69.2067382!2d41.3
            525405"> <i class="fas fa-map-marker-alt"></i> USA </a>
        </div>

        <div class="box">
            <h3>quick links</h3>
            <a href="#home"> <i class="fas fa-arrow-right"></i> home </a>
            <a href="#vehicles"> <i class="fas fa-arrow-right"></i> vehicles </a>
            <a href="#featured"> <i class="fas fa-arrow-right"></i> featured </a>
            <a href="#reviews"> <i class="fas fa-arrow-right"></i> reviews </a>
            <a href="#contact"> <i class="fas fa-arrow-right"></i> contact </a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="tel: +998942413323"> <i class="fas fa-phone"></i> +998(94) 241-33-23 </a>
            <a href="mailto: jamshidtolibjonov3323@gmail.com"> <i class="fas fa-envelope"></i>
                jamshidtolibjonov3323@gmail.com </a>
            <a href="https://www.google.com/maps/dir//Bobir+Akilkhanov+Tech+Academy,+4+University+street,+Tashkent+10019
            4,+%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD/@41.3521626,69.2014573,17z/data=!4m8!4m7!1m0
            !1m5!1m1!1s0x38ae8d4a0dce8309:0x43e0a115d4b09d1a!2m2!1d69.203646!2d41.3521626">
                <i class="fas fa-map-marker-alt"></i> Tashkent, Uzbekistan</a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="https://www.facebook.com/profile.php?id=100076320471172"> <i class="fab fa-facebook-f"></i> facebook </a>
            <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
            <a href="https://www.instagram.com/tolibjonovjamshid"> <i class="fab fa-instagram"></i> instagram </a>
            <a href="https://www.linkedin.com/in/jamshid-tolibjonov-49175423a"> <i class="fab fa-linkedin"></i> linkedin </a>
            <a href="https://pin.it/60FTmcr"> <i class="fab fa-pinterest"></i> pinterest </a>
        </div>

    </div>

    <div class="credit"> created by mr. full stack web developer | Tolibjonov Jamshidjon</div>

</section>

templates/layouts/login_form.html
<div class="login-form-container">

    <span id="close-login-form" class="fas fa-times"></span>

    <form action="">
        <h3>user login</h3>
        <input type="email" placeholder="email" class="box">
        <input type="password" placeholder="password" class="box">
        <p> forget your password <a href="#">click here</a></p>
        <input type="submit" value="login" class="btn">
        <p>or login with</p>
        <div class="buttons">
            <a href="#" class="btn"> google </a>
            <a href="#" class="btn"> facebook </a>
        </div>
        <p> don't have an account <a href="#">create one</a></p>
    </form>

</div>

templates/layouts/navbar.html
<header class="header">

    <div id="menu-btn" class="fas fa-bars"></div>

    <a href="#" class="logo"> <span>max</span>wheels </a>

    <nav class="navbar">
        <a href="#home">home</a>
        <a href="#vehicles">vehicles</a>
        <a href="#featured">featured</a>
        <a href="#reviews">reviews</a>
        <a href="#contact">contact</a>
    </nav>

    <div id="login-btn">
        {% if request.user.is_authenticated %}

        {% else %}
            <button class="btn">login</button>
        {% endif %}
        <i class="far fa-user"></i>
    </div>

</header>